### PR TITLE
refactor!:  require the builder pattern for module initalisation

### PR DESCRIPTION
**Pull request by CommanderStorm**
This PR makes sure that the way structs are constructed is consistent and encourages the builder pattern.
It is based on this question: https://github.com/testcontainers/testcontainers-rs-modules-community/pull/156#discussion_r1660236432

For the changelog:

We now require you to use the builder pattern (instead of some structs being [unit structs](https://doc.rust-lang.org/std/keyword.struct.html)) for all modules.
This ensures that if we add a field in the future that this will not break your existing code. 

This change is breaking for these modules:

| Module | before | after |
|--------|--------|--------|
| `cncf_distribution::CncfDistribution` | `CncfDistribution.start()` | `CncfDistribution::default().start()` |
| `dynamodb_local::DynamoDb` | `DynamoDb.start()` | `DynamoDb::default().start()` |
| `elasticmq::ElasticMq` | `ElasticMq.start()` | `ElasticMq::default().start()` |
| ~`mongo::Mongo`~ (see #143) | ~`Mongo.start()`~ | ~`Mongo::default().start()`~ |
| `kwok::KwokCluster` | `KwokCluster.start()` | `KwokCluster::default().start()` |
| `rabbitmq::RabbitMq` | `RabbitMq.start()` | `RabbitMq::default().start()` |
| `redis::stack::RedisStack` | `RedisStack.start()` | `RedisStack::default().start()` |
| `redis::standalone::Redis` | `Redis.start()` | `Redis::default().start()` |
| `victoria_metrics::VictoriaMetrics` | `VictoriaMetrics.start()` | `VictoriaMetrics::default().start()` |

### CODE REVIEW

**Review by DDtKey — COMMENTED** [review]
I think we can use `refactor` instead of `chore` here

Thank you for the PR! ❤️

**Comment by CommanderStorm** [comment]
> Let's clean this up (rustfmt & etc)

Sorry for that part. Forgot to do rustfmt after doing the (apparently missing doctests) testing run

**Comment by CommanderStorm** [comment]
I don't know why the test for `mssql_server` added in https://github.com/testcontainers/testcontainers-rs-modules-community/pull/72 is failing.

Cannot debug this locally.
@kymmt90 I am assuming you are using this in your testing infra. Is this flaky for you too?

**Comment by DDtKey** [comment]
This is definitely unrelated to the PR and seems to be flaky - yes.

Need to address this but in separate PR for sure

**Pull request merged**
