### PR TITLE
feat: add Hashicorp Vault test container and test

### PR DESCRIPTION
**Pull request by jasondemorrow**
also adds tracing library to dev deps b/c I wanted to see the TC logs and figured others might too

### CODE REVIEW

**Comment by jasondemorrow** [comment]
Tests in untouched code are failing, perhaps due to added tracing dep? That doesn't make sense, but it's all I can think of.

**Comment by jasondemorrow** [comment]
Overrode my local 1.79 with 1.75 to match CI, but now aws-sqs won't build b/c it needs 1.76+?

**Comment by jasondemorrow** [comment]
I see what happened here. I had the distinct misfortune of issuing a PR just as the upgrade to TC 0.18 landed in main :joy:

**Review by DDtKey — APPROVED** [review]
Thank you for the contribution 🚀

And sorry for this inconvenience after `testcontainers` update.

**Pull request merged**
