### PR TITLE
feat: add mariadb module

### PR DESCRIPTION
**Pull request by brianheineman**
This PR adds a module for MariaDB.  I recently added support for MariaDB to [rsql](https://github.com/theseus-rs/rsql/pull/124) and would like to add integration tests for the driver.

### CODE REVIEW

**Review by mervyn-mccreight — APPROVED** [review]
Thanks for the contribution 🚀 .
Looks good to me, I will release it ASAP.

**Comment by brianheineman** [comment]
Thanks for the quick review @mervyn-mccreight and the great project; much appreciated!

**Comment by mervyn-mccreight** [comment]
It is released @brianheineman: https://github.com/testcontainers/testcontainers-rs-modules-community/releases/tag/v0.4.2 🥳

**Comment by brianheineman** [comment]
Wow, thanks for the fast release @mervyn-mccreight!

**Pull request merged**
